### ISSUE TITLE
Build fails due dependency to discontinued module lodash/fp

### ISSUE THREAD

**Issue by smazanek** [daldridge/docusaurus-plugin-lunr#6]
Hi,
starting today, my docusaurus build fails in your plugin with the message
Error: Cannot find module 'lodash/fp'

Could you please fix?

Kind regards
Steffen

**Comment by daldridge** [comment]
Can you provide any more details on your environment?  I have multiple projects which use this plugin, and many others which use lodash, all without issues.  Can you provide your npm install log?

**Comment by daldridge** [comment]
No follow up.  Was potentially a temporary network or npmjs registry issue.  Closing.
